apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: csi-disk      # 华为云CCE云硬盘StorageClass
  resources:
    requests:
      storage: 10Gi